/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ranger.gltf --transform 
Files: Ranger.gltf [2.99MB] > C:\Repos\Kuji\kujidev.github.io\public\models\Ranger-transformed.glb [391.64KB] (87%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Ranger-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh name="Ranger" geometry={nodes.Ranger.geometry} material={materials.Ranger_Texture} skeleton={nodes.Ranger.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Ranger-transformed.glb')
