/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Monk.gltf --transform 
Files: Monk.gltf [2.66MB] > C:\Repos\Kuji\kujidev.github.io\public\models\Monk-transformed.glb [322.27KB] (88%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Monk-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh name="Monk" geometry={nodes.Monk.geometry} material={materials.Monk_Texture} skeleton={nodes.Monk.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Monk-transformed.glb')
