/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Rogue.gltf --transform 
Files: Rogue.gltf [2.57MB] > C:\Repos\Kuji\kujidev.github.io\public\models\Rogue-transformed.glb [344.62KB] (87%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Rogue-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh name="Rogue" geometry={nodes.Rogue.geometry} material={materials.Rogue_Texture} skeleton={nodes.Rogue.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Rogue-transformed.glb')
