/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Warrior.gltf --transform 
Files: Warrior.gltf [3.04MB] > C:\Repos\Kuji\kujidev.github.io\public\models\Warrior-transformed.glb [365.82KB] (88%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Warrior-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh name="Warrior_Body" geometry={nodes.Warrior_Body.geometry} material={materials.Warrior_Texture} skeleton={nodes.Warrior_Body.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Warrior-transformed.glb')
