/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cleric.gltf --transform 
Files: Cleric.gltf [2.99MB] > C:\Repos\Kuji\kujidev.github.io\public\models\Cleric-transformed.glb [338.27KB] (89%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Cleric-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh name="Cleric" geometry={nodes.Cleric.geometry} material={materials.Cleric_Texture} skeleton={nodes.Cleric.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cleric-transformed.glb')
