/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wizard.gltf --transform 
Files: Wizard.gltf [3.3MB] > C:\Repos\Kuji\kujidev.github.io\public\models\Wizard-transformed.glb [436.09KB] (87%)
*/

import React, { useEffect, useRef, useMemo } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { usePlayerState } from '@/hooks/usePlayerState'
import CastingCircle from '@/components/CastingCircle'
import ShieldEffect from '@/components/ShieldEffect'
import ManaShield from '@/components/ManaShield'
import { getElementForAction, ELEMENTS } from '@/config/actions'
import * as THREE from 'three'

// Create glow materials for each element
const GLOW_MATERIALS = {}
Object.values(ELEMENTS).forEach(element => {
  GLOW_MATERIALS[element.id] = new THREE.MeshStandardMaterial({
    color: element.glow,
    emissive: element.glow,
    emissiveIntensity: 4,
    toneMapped: false,
  })
})

export function Model(props) {
  const group = React.useRef()
  const staffMaterialRef = useRef(null)
  const originalStaffMaterialRef = useRef(null)
  const currentActionRef = useRef(null)
  const recastCounterRef = useRef(0) // Track recasts to trigger animation reset
  const { scene, animations: gltfAnimations } = useGLTF('/models/Wizard-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { actions } = useAnimations(gltfAnimations, clone)
  const { animation, state, activeAction, setCastProgress, dispatchAction, tryRecast, STATES, buffs } = usePlayerState()

  // Store reference to staff mesh and cache original material (runs once)
  useEffect(() => {
    clone.traverse((child) => {
      if (!child.isMesh) return
      
      if (child.name.includes('Wizard_Staff')) {
        staffMaterialRef.current = child
        originalStaffMaterialRef.current = child.material.clone()
      }
    })
  }, [clone])

  // Toggle glow based on active action's element
  useEffect(() => {
    if (!staffMaterialRef.current) return

    // Get element for active action
    const element = activeAction ? getElementForAction(activeAction) : null
    
    if (element && state !== STATES.IDLE) {
      // Use element's glow material
      staffMaterialRef.current.material = GLOW_MATERIALS[element.id] || originalStaffMaterialRef.current
    } else {
      // Reset to original
      staffMaterialRef.current.material = originalStaffMaterialRef.current
    }
  }, [state, activeAction, STATES])

  useEffect(() => {
    const currentAction = actions?.[animation]
    if (!currentAction) return

    // Store reference for progress tracking
    currentActionRef.current = currentAction

    // Fade out all other animations and play the current one
    Object.values(actions).forEach((action) => {
      if (action !== currentAction) action?.fadeOut(0.2)
    })

    // For casting/attacking, play once and don't loop
    const isCastingOrAttacking = state === STATES.CASTING || state === STATES.ATTACKING
    if (isCastingOrAttacking) {
      currentAction.setLoop(THREE.LoopOnce, 1)
      currentAction.clampWhenFinished = true
      setCastProgress(0) // Reset progress at start
    } else {
      currentAction.setLoop(THREE.LoopRepeat)
    }

    currentAction.reset().fadeIn(0.2).play()
  }, [animation, actions, state, activeAction, STATES, setCastProgress])

  // Track animation progress for casting bar and auto-finish
  useFrame(() => {
    const action = currentActionRef.current
    if (!action) return

    // Only track progress for casting/attacking states
    if (state === STATES.CASTING || state === STATES.ATTACKING) {
      const duration = action.getClip().duration
      const time = Math.min(action.time, duration) // Clamp to duration
      const progress = time / duration
      setCastProgress(progress)

      // When animation completes, try to recast or finish
      if (progress >= 0.99) {
        // tryRecast returns true if recasting (key held + has mana)
        if (tryRecast()) {
          // Reset animation for recast - no state change needed
          action.reset().play()
          recastCounterRef.current++
        } else {
          dispatchAction('FINISH')
        }
      }
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clone} />
      <CastingCircle position={[0, 0.02, 0]} />
      <ShieldEffect position={[0, 1.5, 0]} />
      <ManaShield position={[0, 1.5, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Wizard-transformed.glb')
