/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wizard.gltf --transform 
Files: Wizard.gltf [3.3MB] > C:\Repos\Kuji\kujidev.github.io\public\models\Wizard-transformed.glb [436.09KB] (87%)
*/

import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { usePlayerState } from '@/hooks/usePlayerState'
import * as THREE from 'three'

export function Model(props) {
  const group = React.useRef()
  const staffMaterialRef = useRef(null)
  const originalMaterialRef = useRef(null)
  const { scene, animations: gltfAnimations } = useGLTF('/models/Wizard-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(gltfAnimations, clone)
  const { animation, state, STATES } = usePlayerState()

  // Store reference to staff mesh and create glow material
  useEffect(() => {
    clone.traverse((child) => {
      if (child.isMesh && child.name.includes('Wizard_Staff')) {
        staffMaterialRef.current = child
        originalMaterialRef.current = child.material.clone()
      }
    })
  }, [clone])

  // Toggle glow based on casting state
  useEffect(() => {
    if (!staffMaterialRef.current) return

    if (state === STATES.CASTING) {
      staffMaterialRef.current.material = new THREE.MeshStandardMaterial({
        color: '#ff6b35',
        emissive: '#ff6b35',
        emissiveIntensity: 3,
        toneMapped: false,
      })
    } else if (state == STATES.ATTACKING) {
      staffMaterialRef.current.material = new THREE.MeshStandardMaterial({
        color: '#4fc3f7',
        emissive: '#4fc3f7',
        emissiveIntensity: 3,
        toneMapped: false,
      })
    } else if (state == STATES.MOVING) {
      staffMaterialRef.current.material = new THREE.MeshStandardMaterial({
        color: '#da70d6',
        emissive: '#da70d6',
        emissiveIntensity: 4,
        toneMapped: false,
      })
    } else {
      staffMaterialRef.current.material = originalMaterialRef.current
    }
  }, [state, STATES])

  useEffect(() => {
    const currentAction = actions?.[animation]
    if (!currentAction) return

    // Fade out all other animations and play the current one
    Object.values(actions).forEach((action) => {
      if (action !== currentAction) action?.fadeOut(0.2)
    })
    
    currentAction.reset().fadeIn(0.2).play()
  }, [animation, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clone} />
    </group>
  )
}

useGLTF.preload('/models/Wizard-transformed.glb')
